CREATE USER test identified BY "test";

GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO test;

GRANT UNLIMITED TABLESPACE TO test;

GRANT CREATE TABLE TO test;

GRANT CREATE SEQUENCE TO test;

GRANT CREATE PROCEDURE TO test;
